### ISSUE TITLE
what are the use case for using boot or scope method?

### ISSUE THREAD

**Issue by michaelnguyen2021** [mtownsend5512/laravel-make-trait#1]
I am not clear when/how `boot` and `scope` method in trait work? Can you please elaborate?

**Comment by imliam** [comment]
When a trait has a method starting with "boot" and ending with the trait's name (ie. trait "DummyTrait" has a method "bootDummyTrait"), Laravel will automatically boot it in the same way as [the first class "boot" method](https://laravel.com/docs/5.7/eloquent#query-scopes) on a regular model. This lets you perform actions like adding global query scopes from a trait.

https://tighten.co/blog/laravel-tip-bootable-model-traits

I'm not sure if anything similar exists for the scope option, though.

**Comment by mtownsend5512** [comment]
Here are two examples, one of a scope trait, and another a boot trait.

```php
namespace App\Traits;

trait FindBySlugOrId
{
    public static function scopefindBySlugOrId($query, $slugOrId)
    {
        if (is_numeric($slugOrId)) {
            return $query->where('id', (int) $slugOrId)->firstOrFail();
        }
        return $query->where('slug', (string) $slugOrId)->firstOrFail();
    }
}
```

When applied to a model, you could do this: ``App\Post::findBySlugOrId($slugOrId);``

Now, for a boot trait.

```php
namespace App\Traits;

trait TrackChanges
{
    public $changes;

    public static function bootTrackChanges()
    {
        static::updating(function ($model) {
            $changes = [];

            foreach ($model->getDirty() as $key => $value) {
                $original = $model->getOriginal($key);

                 $changes[$key] = [
                    'old' => $original,
                    'new' => $value,
                 ];
            }

            $model->changes = $changes;
        });
    }
}
```

This trait will allow you to track the last update done to a model. Let's say you updated a user model record. The original ``name`` was ``David``, and you just changed it to ``Ted``. You could access the previous name by doing something like ``$user->changes`` and you would get

```php
[
   'old' => 'David',
   'new' => 'Ted'
]
```

**Comment by mtownsend5512** [comment]
Here's an example of a regular trait. It gets the model's table columns

```php
namespace App\Traits;

trait TableColumns
{
    public function getTableColumnsAttribute()
    {
        return $this->getConnection()->getSchemaBuilder()->getColumnListing($this->getTable());
    }
}
```

And then you can grab the model's columns by doing ``$model->table_columns`` and get an array.

**Comment by michaelnguyen2021** [comment]
thanks @mtownsend5512 for sharing. I close the issue. Please feel free to add more use cases to benefit the community.
