### ISSUE TITLE
Incompatible with PHP version 8

### ISSUE THREAD

**Issue by sosthenehounsokou** [mtownsend5512/laravel-make-trait#2]
Hello.

When I run this command : composer require mtownsend/laravel-make-trait,

I get this error : [InvalidArgumentException] Package mtownsend/laravel-make-trait has a PHP requirement incompatible with your PHP version, PHP extensions and Composer version

I use Laravel 8 , Composer 2.0.4 and PHP 8

**Comment by mtownsend5512** [comment]
Package has been updated to support PHP 8
